name: full_demo
description: A Flutter Dashboard Template.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dashboard_widgets:
    git: https://github.com/asas-tech/dashboard_widgets.git

  # Localizations   
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # stacked Architecture
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  stacked_themes: ^0.3.8+1

 # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.0

 # Navigation 
  vrouter: ^1.2.0+11

  # Fonts and Icons
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2

  # Local Storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8

  # Network
  http: ^0.13.3
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  stacked_generator: ^0.5.6
  build_runner: ^2.1.2
  injectable_generator: ^1.5.2


flutter:
  uses-material-design: true

  assets:
    - assets/logo/

 
flutter_intl:
  enabled: true
